services:
  martin.emptypostsubjects.listener:
    class: martin\emptypostsubjects\event\listener
    arguments:
      - @template
      - @config
      - @user
      - @auth
    tags:
      - { name: event.listener }
